version: '3.6'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  # node:
  #   build: ./docker/node
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo