version: '3.6'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-seed:
    build: ./docker/mongo-seed
    links:
      - mongodb
  # node:
  #   build: ./docker/node
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo