version: '3.6'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./docker/mongo-seed
    links:
      - mongodb
  node:
    image: node:8.10.0-alpine
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - mongodb
      - mongo-seed
    working_dir: /app
    command: node server.js